stages:
  - test
  - publish

image: node:dubnium

include:
  template: Dependency-Scanning.gitlab-ci.yml

.test: &test
  image: zenika/alpine-chrome:with-node
  stage: test
  script:
    - npm ci
    - cd packages/recorder && npm ci && cd -
    - npm run lint
    - npm run test

.publish: &publish
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - npm publish --access public

test merge request:
  <<: *test
  only:
    - merge_request

test master:
  <<: *test
  only:
    - master

test tag:
  <<: *test
  only:
    - tags

publish tag:
  <<: *publish
  only:
    - tags
