stages:
  - test
  - deploy

image: node:dubnium

include:
  template: Dependency-Scanning.gitlab-ci.yml

.test: &test
  image: zenika/alpine-chrome:with-node
  stage: test
  script:
    - npm ci
    - npm run lint
    - npm run test

.deploy:
  stage: deploy
  script:
    - npm publish

test merge request:
  <<: *test
  only:
    - merge_request

test master:
  <<: *test
  only:
    - master

test tag:
  <<: *test
  only:
    - tags
