window.esdocSearchIndex = [
  [
    "itslanguage/src/administrative-sdk/administrative-sdk.js~administrativesdk",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html",
    "<span>AdministrativeSDK</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/administrative-sdk.js</span>",
    "class"
  ],
  [
    "itslanguage/src/audio/audio-player.js~audioplayer",
    "class/src/audio/audio-player.js~AudioPlayer.html",
    "<span>AudioPlayer</span> <span class=\"search-result-import-path\">itslanguage/src/audio/audio-player.js</span>",
    "class"
  ],
  [
    "itslanguage/src/audio/audio-recorder.js~audiorecorder",
    "class/src/audio/audio-recorder.js~AudioRecorder.html",
    "<span>AudioRecorder</span> <span class=\"search-result-import-path\">itslanguage/src/audio/audio-recorder.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/basic-auth/basic-auth.js~basicauth",
    "class/src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth.html",
    "<span>BasicAuth</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/basic-auth/basic-auth.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/category/category.js~category",
    "class/src/administrative-sdk/category/category.js~Category.html",
    "<span>Category</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/category/category.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/choice-challenge/choice-challenge.js~choicechallenge",
    "class/src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge.html",
    "<span>ChoiceChallenge</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/choice-challenge/choice-challenge.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html",
    "<span>ChoiceRecognition</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/choice-recognition/choice-recognition.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/connection/connection-controller.js~connection",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html",
    "<span>Connection</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/connection/connection-controller.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/email-credentials/email-credentials.js~emailcredentials",
    "class/src/administrative-sdk/email-credentials/email-credentials.js~EmailCredentials.html",
    "<span>EmailCredentials</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/email-credentials/email-credentials.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/group/group.js~group",
    "class/src/administrative-sdk/group/group.js~Group.html",
    "<span>Group</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/group/group.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/organisation/organisation.js~organisation",
    "class/src/administrative-sdk/organisation/organisation.js~Organisation.html",
    "<span>Organisation</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/organisation/organisation.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/phoneme/phoneme.js~phoneme",
    "class/src/administrative-sdk/phoneme/phoneme.js~Phoneme.html",
    "<span>Phoneme</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/phoneme/phoneme.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/profile/profile.js~profile",
    "class/src/administrative-sdk/profile/profile.js~Profile.html",
    "<span>Profile</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/profile/profile.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/progress/progress.js~progress",
    "class/src/administrative-sdk/progress/progress.js~Progress.html",
    "<span>Progress</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/progress/progress.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html",
    "<span>PronunciationAnalysis</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~pronunciationchallenge",
    "class/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge.html",
    "<span>PronunciationChallenge</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/role/role.js~role",
    "class/src/administrative-sdk/role/role.js~Role.html",
    "<span>Role</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/role/role.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/speech-challenge/speech-challenge.js~speechchallenge",
    "class/src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge.html",
    "<span>SpeechChallenge</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/speech-challenge/speech-challenge.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/speech-recording/speech-recording.js~speechrecording",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html",
    "<span>SpeechRecording</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/speech-recording/speech-recording.js</span>",
    "class"
  ],
  [
    "itslanguage/src/audio/tools.js~stopwatch",
    "class/src/audio/tools.js~Stopwatch.html",
    "<span>Stopwatch</span> <span class=\"search-result-import-path\">itslanguage/src/audio/tools.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/user/user.js~user",
    "class/src/administrative-sdk/user/user.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/user/user.js</span>",
    "class"
  ],
  [
    "itslanguage/src/audio/audio-tools.js~volumemeter",
    "class/src/audio/audio-tools.js~VolumeMeter.html",
    "<span>VolumeMeter</span> <span class=\"search-result-import-path\">itslanguage/src/audio/audio-tools.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/word/word.js~word",
    "class/src/administrative-sdk/word/word.js~Word.html",
    "<span>Word</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/word/word.js</span>",
    "class"
  ],
  [
    "itslanguage/src/administrative-sdk/word-chunk/word-chunk.js~wordchunk",
    "class/src/administrative-sdk/word-chunk/word-chunk.js~WordChunk.html",
    "<span>WordChunk</span> <span class=\"search-result-import-path\">itslanguage/src/administrative-sdk/word-chunk/word-chunk.js</span>",
    "class"
  ],
  [
    "itslanguage/src/audio/audio-tools.js~generatewavesample",
    "function/index.html#static-function-generateWaveSample",
    "<span>generateWaveSample</span> <span class=\"search-result-import-path\">itslanguage/src/audio/audio-tools.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js",
    "file/src/administrative-sdk/administrative-sdk.js.html",
    "src/administrative-sdk/administrative-sdk.js",
    "file"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#constructor",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-constructor-constructor",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#createchoicechallenge",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-createChoiceChallenge",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#createChoiceChallenge",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#createemailcredentials",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-createEmailCredentials",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#createEmailCredentials",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#createorganisation",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-createOrganisation",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#createOrganisation",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#createpronunciationchallenge",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-createPronunciationChallenge",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#createPronunciationChallenge",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#createspeechchallenge",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-createSpeechChallenge",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#createSpeechChallenge",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#createuser",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-createUser",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#createUser",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#deletepronunciationchallenge",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-deletePronunciationChallenge",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#deletePronunciationChallenge",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getchoicechallenge",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getChoiceChallenge",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getChoiceChallenge",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getchoicechallenges",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getChoiceChallenges",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getChoiceChallenges",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getchoicerecognition",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getChoiceRecognition",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getChoiceRecognition",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getchoicerecognitions",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getChoiceRecognitions",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getChoiceRecognitions",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getcurrentuser",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getCurrentUser",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getCurrentUser",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getorganisation",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getOrganisation",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getOrganisation",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getorganisations",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getOrganisations",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getOrganisations",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getprofile",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getProfile",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getProfile",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getprofiles",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getProfiles",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getProfiles",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getpronunciationanalyses",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getPronunciationAnalyses",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getPronunciationAnalyses",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getpronunciationanalysis",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getPronunciationAnalysis",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getPronunciationAnalysis",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getpronunciationchallenge",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getPronunciationChallenge",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getPronunciationChallenge",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getpronunciationchallenges",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getPronunciationChallenges",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getPronunciationChallenges",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getrole",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getRole",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getRole",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getroles",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getRoles",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getRoles",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getspeechchallenge",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getSpeechChallenge",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getSpeechChallenge",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getspeechchallenges",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getSpeechChallenges",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getSpeechChallenges",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getspeechrecording",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getSpeechRecording",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getSpeechRecording",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getspeechrecordings",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getSpeechRecordings",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getSpeechRecordings",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getuser",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getUser",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getUser",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#getusers",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-getUsers",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#getUsers",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#startstreamingchoicerecognition",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-startStreamingChoiceRecognition",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#startStreamingChoiceRecognition",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#startstreamingpronunciationanalysis",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-startStreamingPronunciationAnalysis",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#startStreamingPronunciationAnalysis",
    "method"
  ],
  [
    "src/administrative-sdk/administrative-sdk.js~administrativesdk#startstreamingspeechrecording",
    "class/src/administrative-sdk/administrative-sdk.js~AdministrativeSDK.html#instance-method-startStreamingSpeechRecording",
    "src/administrative-sdk/administrative-sdk.js~AdministrativeSDK#startStreamingSpeechRecording",
    "method"
  ],
  [
    "src/administrative-sdk/basic-auth/basic-auth.js",
    "file/src/administrative-sdk/basic-auth/basic-auth.js.html",
    "src/administrative-sdk/basic-auth/basic-auth.js",
    "file"
  ],
  [
    "src/administrative-sdk/basic-auth/basic-auth.js~basicauth#constructor",
    "class/src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth.html#instance-constructor-constructor",
    "src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/basic-auth/basic-auth.js~basicauth#credentials",
    "class/src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth.html#instance-member-credentials",
    "src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth#credentials",
    "member"
  ],
  [
    "src/administrative-sdk/basic-auth/basic-auth.js~basicauth#principal",
    "class/src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth.html#instance-member-principal",
    "src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth#principal",
    "member"
  ],
  [
    "src/administrative-sdk/basic-auth/basic-auth.js~basicauth#tenantid",
    "class/src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth.html#instance-member-tenantId",
    "src/administrative-sdk/basic-auth/basic-auth.js~BasicAuth#tenantId",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js",
    "file/src/administrative-sdk/category/category.js.html",
    "src/administrative-sdk/category/category.js",
    "file"
  ],
  [
    "src/administrative-sdk/category/category.js~category#categories",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-categories",
    "src/administrative-sdk/category/category.js~Category#categories",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#color",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-color",
    "src/administrative-sdk/category/category.js~Category#color",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#constructor",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-constructor-constructor",
    "src/administrative-sdk/category/category.js~Category#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/category/category.js~category#description",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-description",
    "src/administrative-sdk/category/category.js~Category#description",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#icon",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-icon",
    "src/administrative-sdk/category/category.js~Category#icon",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#id",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-id",
    "src/administrative-sdk/category/category.js~Category#id",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#image",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-image",
    "src/administrative-sdk/category/category.js~Category#image",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#name",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-name",
    "src/administrative-sdk/category/category.js~Category#name",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#progress",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-progress",
    "src/administrative-sdk/category/category.js~Category#progress",
    "member"
  ],
  [
    "src/administrative-sdk/category/category.js~category#speechchallenges",
    "class/src/administrative-sdk/category/category.js~Category.html#instance-member-speechChallenges",
    "src/administrative-sdk/category/category.js~Category#speechChallenges",
    "member"
  ],
  [
    "src/administrative-sdk/choice-challenge/choice-challenge-controller.js",
    "file/src/administrative-sdk/choice-challenge/choice-challenge-controller.js.html",
    "src/administrative-sdk/choice-challenge/choice-challenge-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/choice-challenge/choice-challenge.js",
    "file/src/administrative-sdk/choice-challenge/choice-challenge.js.html",
    "src/administrative-sdk/choice-challenge/choice-challenge.js",
    "file"
  ],
  [
    "src/administrative-sdk/choice-challenge/choice-challenge.js~choicechallenge#choices",
    "class/src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge.html#instance-member-choices",
    "src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge#choices",
    "member"
  ],
  [
    "src/administrative-sdk/choice-challenge/choice-challenge.js~choicechallenge#constructor",
    "class/src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge.html#instance-constructor-constructor",
    "src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/choice-challenge/choice-challenge.js~choicechallenge#id",
    "class/src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge.html#instance-member-id",
    "src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge#id",
    "member"
  ],
  [
    "src/administrative-sdk/choice-challenge/choice-challenge.js~choicechallenge#question",
    "class/src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge.html#instance-member-question",
    "src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge#question",
    "member"
  ],
  [
    "src/administrative-sdk/choice-challenge/choice-challenge.js~choicechallenge#status",
    "class/src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge.html#instance-member-status",
    "src/administrative-sdk/choice-challenge/choice-challenge.js~ChoiceChallenge#status",
    "member"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition-controller.js",
    "file/src/administrative-sdk/choice-recognition/choice-recognition-controller.js.html",
    "src/administrative-sdk/choice-recognition/choice-recognition-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js",
    "file/src/administrative-sdk/choice-recognition/choice-recognition.js.html",
    "src/administrative-sdk/choice-recognition/choice-recognition.js",
    "file"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#audiourl",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-member-audioUrl",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#audioUrl",
    "member"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#challengeid",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-member-challengeId",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#challengeId",
    "member"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#constructor",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-constructor-constructor",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#created",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-member-created",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#created",
    "member"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#id",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-member-id",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#id",
    "member"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#recognised",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-member-recognised",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#recognised",
    "member"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#updated",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-member-updated",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#updated",
    "member"
  ],
  [
    "src/administrative-sdk/choice-recognition/choice-recognition.js~choicerecognition#userid",
    "class/src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition.html#instance-member-userId",
    "src/administrative-sdk/choice-recognition/choice-recognition.js~ChoiceRecognition#userId",
    "member"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js",
    "file/src/administrative-sdk/connection/connection-controller.js.html",
    "src/administrative-sdk/connection/connection-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#addaccesstoken",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-addAccessToken",
    "src/administrative-sdk/connection/connection-controller.js~Connection#addAccessToken",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#addeventlistener",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-addEventListener",
    "src/administrative-sdk/connection/connection-controller.js~Connection#addEventListener",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#cancelstreaming",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-cancelStreaming",
    "src/administrative-sdk/connection/connection-controller.js~Connection#cancelStreaming",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#constructor",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-constructor-constructor",
    "src/administrative-sdk/connection/connection-controller.js~Connection#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#getoauth2token",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-getOauth2Token",
    "src/administrative-sdk/connection/connection-controller.js~Connection#getOauth2Token",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#getuserauth",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-getUserAuth",
    "src/administrative-sdk/connection/connection-controller.js~Connection#getUserAuth",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#handleresponse",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-handleResponse",
    "src/administrative-sdk/connection/connection-controller.js~Connection#handleResponse",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#removeeventlistener",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-removeEventListener",
    "src/administrative-sdk/connection/connection-controller.js~Connection#removeEventListener",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#websocketconnect",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-webSocketConnect",
    "src/administrative-sdk/connection/connection-controller.js~Connection#webSocketConnect",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection#websocketdisconnect",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#instance-method-webSocketDisconnect",
    "src/administrative-sdk/connection/connection-controller.js~Connection#webSocketDisconnect",
    "method"
  ],
  [
    "src/administrative-sdk/connection/connection-controller.js~connection.logrpcerror",
    "class/src/administrative-sdk/connection/connection-controller.js~Connection.html#static-method-logRPCError",
    "src/administrative-sdk/connection/connection-controller.js~Connection.logRPCError",
    "method"
  ],
  [
    "src/administrative-sdk/email-credentials/email-credentials-controller.js",
    "file/src/administrative-sdk/email-credentials/email-credentials-controller.js.html",
    "src/administrative-sdk/email-credentials/email-credentials-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/email-credentials/email-credentials.js",
    "file/src/administrative-sdk/email-credentials/email-credentials.js.html",
    "src/administrative-sdk/email-credentials/email-credentials.js",
    "file"
  ],
  [
    "src/administrative-sdk/email-credentials/email-credentials.js~emailcredentials#constructor",
    "class/src/administrative-sdk/email-credentials/email-credentials.js~EmailCredentials.html#instance-constructor-constructor",
    "src/administrative-sdk/email-credentials/email-credentials.js~EmailCredentials#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/email-credentials/email-credentials.js~emailcredentials#email",
    "class/src/administrative-sdk/email-credentials/email-credentials.js~EmailCredentials.html#instance-member-email",
    "src/administrative-sdk/email-credentials/email-credentials.js~EmailCredentials#email",
    "member"
  ],
  [
    "src/administrative-sdk/email-credentials/email-credentials.js~emailcredentials#password",
    "class/src/administrative-sdk/email-credentials/email-credentials.js~EmailCredentials.html#instance-member-password",
    "src/administrative-sdk/email-credentials/email-credentials.js~EmailCredentials#password",
    "member"
  ],
  [
    "src/administrative-sdk/group/group.js",
    "file/src/administrative-sdk/group/group.js.html",
    "src/administrative-sdk/group/group.js",
    "file"
  ],
  [
    "src/administrative-sdk/group/group.js~group#constructor",
    "class/src/administrative-sdk/group/group.js~Group.html#instance-constructor-constructor",
    "src/administrative-sdk/group/group.js~Group#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/group/group.js~group#id",
    "class/src/administrative-sdk/group/group.js~Group.html#instance-member-id",
    "src/administrative-sdk/group/group.js~Group#id",
    "member"
  ],
  [
    "src/administrative-sdk/group/group.js~group#name",
    "class/src/administrative-sdk/group/group.js~Group.html#instance-member-name",
    "src/administrative-sdk/group/group.js~Group#name",
    "member"
  ],
  [
    "src/administrative-sdk/organisation/organisation-controller.js",
    "file/src/administrative-sdk/organisation/organisation-controller.js.html",
    "src/administrative-sdk/organisation/organisation-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/organisation/organisation.js",
    "file/src/administrative-sdk/organisation/organisation.js.html",
    "src/administrative-sdk/organisation/organisation.js",
    "file"
  ],
  [
    "src/administrative-sdk/organisation/organisation.js~organisation#constructor",
    "class/src/administrative-sdk/organisation/organisation.js~Organisation.html#instance-constructor-constructor",
    "src/administrative-sdk/organisation/organisation.js~Organisation#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/organisation/organisation.js~organisation#id",
    "class/src/administrative-sdk/organisation/organisation.js~Organisation.html#instance-member-id",
    "src/administrative-sdk/organisation/organisation.js~Organisation#id",
    "member"
  ],
  [
    "src/administrative-sdk/organisation/organisation.js~organisation#name",
    "class/src/administrative-sdk/organisation/organisation.js~Organisation.html#instance-member-name",
    "src/administrative-sdk/organisation/organisation.js~Organisation#name",
    "member"
  ],
  [
    "src/administrative-sdk/phoneme/phoneme.js",
    "file/src/administrative-sdk/phoneme/phoneme.js.html",
    "src/administrative-sdk/phoneme/phoneme.js",
    "file"
  ],
  [
    "src/administrative-sdk/phoneme/phoneme.js~phoneme#confidencescore",
    "class/src/administrative-sdk/phoneme/phoneme.js~Phoneme.html#instance-member-confidenceScore",
    "src/administrative-sdk/phoneme/phoneme.js~Phoneme#confidenceScore",
    "member"
  ],
  [
    "src/administrative-sdk/phoneme/phoneme.js~phoneme#constructor",
    "class/src/administrative-sdk/phoneme/phoneme.js~Phoneme.html#instance-constructor-constructor",
    "src/administrative-sdk/phoneme/phoneme.js~Phoneme#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/phoneme/phoneme.js~phoneme#ipa",
    "class/src/administrative-sdk/phoneme/phoneme.js~Phoneme.html#instance-member-ipa",
    "src/administrative-sdk/phoneme/phoneme.js~Phoneme#ipa",
    "member"
  ],
  [
    "src/administrative-sdk/phoneme/phoneme.js~phoneme#score",
    "class/src/administrative-sdk/phoneme/phoneme.js~Phoneme.html#instance-member-score",
    "src/administrative-sdk/phoneme/phoneme.js~Phoneme#score",
    "member"
  ],
  [
    "src/administrative-sdk/phoneme/phoneme.js~phoneme#verdict",
    "class/src/administrative-sdk/phoneme/phoneme.js~Phoneme.html#instance-member-verdict",
    "src/administrative-sdk/phoneme/phoneme.js~Phoneme#verdict",
    "member"
  ],
  [
    "src/administrative-sdk/profile/profile-controller.js",
    "file/src/administrative-sdk/profile/profile-controller.js.html",
    "src/administrative-sdk/profile/profile-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/profile/profile.js",
    "file/src/administrative-sdk/profile/profile.js.html",
    "src/administrative-sdk/profile/profile.js",
    "file"
  ],
  [
    "src/administrative-sdk/profile/profile.js~profile#birthdate",
    "class/src/administrative-sdk/profile/profile.js~Profile.html#instance-member-birthDate",
    "src/administrative-sdk/profile/profile.js~Profile#birthDate",
    "member"
  ],
  [
    "src/administrative-sdk/profile/profile.js~profile#constructor",
    "class/src/administrative-sdk/profile/profile.js~Profile.html#instance-constructor-constructor",
    "src/administrative-sdk/profile/profile.js~Profile#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/profile/profile.js~profile#firstname",
    "class/src/administrative-sdk/profile/profile.js~Profile.html#instance-member-firstName",
    "src/administrative-sdk/profile/profile.js~Profile#firstName",
    "member"
  ],
  [
    "src/administrative-sdk/profile/profile.js~profile#gender",
    "class/src/administrative-sdk/profile/profile.js~Profile.html#instance-member-gender",
    "src/administrative-sdk/profile/profile.js~Profile#gender",
    "member"
  ],
  [
    "src/administrative-sdk/profile/profile.js~profile#infix",
    "class/src/administrative-sdk/profile/profile.js~Profile.html#instance-member-infix",
    "src/administrative-sdk/profile/profile.js~Profile#infix",
    "member"
  ],
  [
    "src/administrative-sdk/profile/profile.js~profile#lastname",
    "class/src/administrative-sdk/profile/profile.js~Profile.html#instance-member-lastName",
    "src/administrative-sdk/profile/profile.js~Profile#lastName",
    "member"
  ],
  [
    "src/administrative-sdk/progress/progress.js",
    "file/src/administrative-sdk/progress/progress.js.html",
    "src/administrative-sdk/progress/progress.js",
    "file"
  ],
  [
    "src/administrative-sdk/progress/progress.js~progress#constructor",
    "class/src/administrative-sdk/progress/progress.js~Progress.html#instance-constructor-constructor",
    "src/administrative-sdk/progress/progress.js~Progress#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/progress/progress.js~progress#done",
    "class/src/administrative-sdk/progress/progress.js~Progress.html#instance-member-done",
    "src/administrative-sdk/progress/progress.js~Progress#done",
    "member"
  ],
  [
    "src/administrative-sdk/progress/progress.js~progress#total",
    "class/src/administrative-sdk/progress/progress.js~Progress.html#instance-member-total",
    "src/administrative-sdk/progress/progress.js~Progress#total",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js",
    "file/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js.html",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js",
    "file/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js.html",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js",
    "file"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#audiourl",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-audioUrl",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#audioUrl",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#challengeid",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-challengeId",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#challengeId",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#confidencescore",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-confidenceScore",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#confidenceScore",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#constructor",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-constructor-constructor",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#created",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-created",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#created",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#id",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-id",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#id",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#score",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-score",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#score",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#updated",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-updated",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#updated",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#userid",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-userId",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#userId",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~pronunciationanalysis#words",
    "class/src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis.html#instance-member-words",
    "src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js~PronunciationAnalysis#words",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js",
    "file/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js.html",
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js",
    "file/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js.html",
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js",
    "file"
  ],
  [
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~pronunciationchallenge#constructor",
    "class/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge.html#instance-constructor-constructor",
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~pronunciationchallenge#id",
    "class/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge.html#instance-member-id",
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge#id",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~pronunciationchallenge#referenceaudiourl",
    "class/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge.html#instance-member-referenceAudioUrl",
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge#referenceAudioUrl",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~pronunciationchallenge#status",
    "class/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge.html#instance-member-status",
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge#status",
    "member"
  ],
  [
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~pronunciationchallenge#transcription",
    "class/src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge.html#instance-member-transcription",
    "src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js~PronunciationChallenge#transcription",
    "member"
  ],
  [
    "src/administrative-sdk/role/role-controller.js",
    "file/src/administrative-sdk/role/role-controller.js.html",
    "src/administrative-sdk/role/role-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/role/role.js",
    "file/src/administrative-sdk/role/role.js.html",
    "src/administrative-sdk/role/role.js",
    "file"
  ],
  [
    "src/administrative-sdk/role/role.js~role#constructor",
    "class/src/administrative-sdk/role/role.js~Role.html#instance-constructor-constructor",
    "src/administrative-sdk/role/role.js~Role#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/role/role.js~role#name",
    "class/src/administrative-sdk/role/role.js~Role.html#instance-member-name",
    "src/administrative-sdk/role/role.js~Role#name",
    "member"
  ],
  [
    "src/administrative-sdk/role/role.js~role#permissions",
    "class/src/administrative-sdk/role/role.js~Role.html#instance-member-permissions",
    "src/administrative-sdk/role/role.js~Role#permissions",
    "member"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge-controller.js",
    "file/src/administrative-sdk/speech-challenge/speech-challenge-controller.js.html",
    "src/administrative-sdk/speech-challenge/speech-challenge-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge.js",
    "file/src/administrative-sdk/speech-challenge/speech-challenge.js.html",
    "src/administrative-sdk/speech-challenge/speech-challenge.js",
    "file"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge.js~speechchallenge#constructor",
    "class/src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge.html#instance-constructor-constructor",
    "src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge.js~speechchallenge#id",
    "class/src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge.html#instance-member-id",
    "src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge#id",
    "member"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge.js~speechchallenge#imageurl",
    "class/src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge.html#instance-member-imageUrl",
    "src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge#imageUrl",
    "member"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge.js~speechchallenge#referenceaudiourl",
    "class/src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge.html#instance-member-referenceAudioUrl",
    "src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge#referenceAudioUrl",
    "member"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge.js~speechchallenge#srturl",
    "class/src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge.html#instance-member-srtUrl",
    "src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge#srtUrl",
    "member"
  ],
  [
    "src/administrative-sdk/speech-challenge/speech-challenge.js~speechchallenge#topic",
    "class/src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge.html#instance-member-topic",
    "src/administrative-sdk/speech-challenge/speech-challenge.js~SpeechChallenge#topic",
    "member"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording-controller.js",
    "file/src/administrative-sdk/speech-recording/speech-recording-controller.js.html",
    "src/administrative-sdk/speech-recording/speech-recording-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js",
    "file/src/administrative-sdk/speech-recording/speech-recording.js.html",
    "src/administrative-sdk/speech-recording/speech-recording.js",
    "file"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js~speechrecording#audiourl",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html#instance-member-audioUrl",
    "src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording#audioUrl",
    "member"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js~speechrecording#challengeid",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html#instance-member-challengeId",
    "src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording#challengeId",
    "member"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js~speechrecording#constructor",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html#instance-constructor-constructor",
    "src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js~speechrecording#created",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html#instance-member-created",
    "src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording#created",
    "member"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js~speechrecording#id",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html#instance-member-id",
    "src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording#id",
    "member"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js~speechrecording#updated",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html#instance-member-updated",
    "src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording#updated",
    "member"
  ],
  [
    "src/administrative-sdk/speech-recording/speech-recording.js~speechrecording#userid",
    "class/src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording.html#instance-member-userId",
    "src/administrative-sdk/speech-recording/speech-recording.js~SpeechRecording#userId",
    "member"
  ],
  [
    "src/administrative-sdk/user/user-controller.js",
    "file/src/administrative-sdk/user/user-controller.js.html",
    "src/administrative-sdk/user/user-controller.js",
    "file"
  ],
  [
    "src/administrative-sdk/user/user.js",
    "file/src/administrative-sdk/user/user.js.html",
    "src/administrative-sdk/user/user.js",
    "file"
  ],
  [
    "src/administrative-sdk/user/user.js~user#constructor",
    "class/src/administrative-sdk/user/user.js~User.html#instance-constructor-constructor",
    "src/administrative-sdk/user/user.js~User#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/user/user.js~user#created",
    "class/src/administrative-sdk/user/user.js~User.html#instance-member-created",
    "src/administrative-sdk/user/user.js~User#created",
    "member"
  ],
  [
    "src/administrative-sdk/user/user.js~user#groups",
    "class/src/administrative-sdk/user/user.js~User.html#instance-member-groups",
    "src/administrative-sdk/user/user.js~User#groups",
    "member"
  ],
  [
    "src/administrative-sdk/user/user.js~user#id",
    "class/src/administrative-sdk/user/user.js~User.html#instance-member-id",
    "src/administrative-sdk/user/user.js~User#id",
    "member"
  ],
  [
    "src/administrative-sdk/user/user.js~user#profile",
    "class/src/administrative-sdk/user/user.js~User.html#instance-member-profile",
    "src/administrative-sdk/user/user.js~User#profile",
    "member"
  ],
  [
    "src/administrative-sdk/user/user.js~user#roles",
    "class/src/administrative-sdk/user/user.js~User.html#instance-member-roles",
    "src/administrative-sdk/user/user.js~User#roles",
    "member"
  ],
  [
    "src/administrative-sdk/user/user.js~user#updated",
    "class/src/administrative-sdk/user/user.js~User.html#instance-member-updated",
    "src/administrative-sdk/user/user.js~User#updated",
    "member"
  ],
  [
    "src/administrative-sdk/utils/base64-utils.js",
    "file/src/administrative-sdk/utils/base64-utils.js.html",
    "src/administrative-sdk/utils/base64-utils.js",
    "file"
  ],
  [
    "src/administrative-sdk/word-chunk/word-chunk.js",
    "file/src/administrative-sdk/word-chunk/word-chunk.js.html",
    "src/administrative-sdk/word-chunk/word-chunk.js",
    "file"
  ],
  [
    "src/administrative-sdk/word-chunk/word-chunk.js~wordchunk#constructor",
    "class/src/administrative-sdk/word-chunk/word-chunk.js~WordChunk.html#instance-constructor-constructor",
    "src/administrative-sdk/word-chunk/word-chunk.js~WordChunk#constructor",
    "method"
  ],
  [
    "src/administrative-sdk/word-chunk/word-chunk.js~wordchunk#graphemes",
    "class/src/administrative-sdk/word-chunk/word-chunk.js~WordChunk.html#instance-member-graphemes",
    "src/administrative-sdk/word-chunk/word-chunk.js~WordChunk#graphemes",
    "member"
  ],
  [
    "src/administrative-sdk/word-chunk/word-chunk.js~wordchunk#phonemes",
    "class/src/administrative-sdk/word-chunk/word-chunk.js~WordChunk.html#instance-member-phonemes",
    "src/administrative-sdk/word-chunk/word-chunk.js~WordChunk#phonemes",
    "member"
  ],
  [
    "src/administrative-sdk/word-chunk/word-chunk.js~wordchunk#score",
    "class/src/administrative-sdk/word-chunk/word-chunk.js~WordChunk.html#instance-member-score",
    "src/administrative-sdk/word-chunk/word-chunk.js~WordChunk#score",
    "member"
  ],
  [
    "src/administrative-sdk/word-chunk/word-chunk.js~wordchunk#verdict",
    "class/src/administrative-sdk/word-chunk/word-chunk.js~WordChunk.html#instance-member-verdict",
    "src/administrative-sdk/word-chunk/word-chunk.js~WordChunk#verdict",
    "member"
  ],
  [
    "src/administrative-sdk/word/word.js",
    "file/src/administrative-sdk/word/word.js.html",
    "src/administrative-sdk/word/word.js",
    "file"
  ],
  [
    "src/administrative-sdk/word/word.js~word#chunks",
    "class/src/administrative-sdk/word/word.js~Word.html#instance-member-chunks",
    "src/administrative-sdk/word/word.js~Word#chunks",
    "member"
  ],
  [
    "src/administrative-sdk/word/word.js~word#constructor",
    "class/src/administrative-sdk/word/word.js~Word.html#instance-constructor-constructor",
    "src/administrative-sdk/word/word.js~Word#constructor",
    "method"
  ],
  [
    "src/audio/audio-player.js",
    "file/src/audio/audio-player.js.html",
    "src/audio/audio-player.js",
    "file"
  ],
  [
    "src/audio/audio-player.js~audioplayer#addeventlistener",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-addEventListener",
    "src/audio/audio-player.js~AudioPlayer#addEventListener",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#bindstopwatch",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-bindStopwatch",
    "src/audio/audio-player.js~AudioPlayer#bindStopwatch",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#canplay",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-canPlay",
    "src/audio/audio-player.js~AudioPlayer#canPlay",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#canuseaudio",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-canUseAudio",
    "src/audio/audio-player.js~AudioPlayer#canUseAudio",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#canusecordovamedia",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-canUseCordovaMedia",
    "src/audio/audio-player.js~AudioPlayer#canUseCordovaMedia",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#constructor",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-constructor-constructor",
    "src/audio/audio-player.js~AudioPlayer#constructor",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getaudiovolume",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getAudioVolume",
    "src/audio/audio-player.js~AudioPlayer#getAudioVolume",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getbufferfill",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getBufferFill",
    "src/audio/audio-player.js~AudioPlayer#getBufferFill",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getcurrenttime",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getCurrentTime",
    "src/audio/audio-player.js~AudioPlayer#getCurrentTime",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getduration",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getDuration",
    "src/audio/audio-player.js~AudioPlayer#getDuration",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getplaybackrate",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getPlaybackRate",
    "src/audio/audio-player.js~AudioPlayer#getPlaybackRate",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#isaudiomuted",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-isAudioMuted",
    "src/audio/audio-player.js~AudioPlayer#isAudioMuted",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#isplaying",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-isPlaying",
    "src/audio/audio-player.js~AudioPlayer#isPlaying",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#load",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-load",
    "src/audio/audio-player.js~AudioPlayer#load",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#pause",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-pause",
    "src/audio/audio-player.js~AudioPlayer#pause",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#play",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-play",
    "src/audio/audio-player.js~AudioPlayer#play",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#preload",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-preload",
    "src/audio/audio-player.js~AudioPlayer#preload",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#removeeventlistener",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-removeEventListener",
    "src/audio/audio-player.js~AudioPlayer#removeEventListener",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#reset",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-reset",
    "src/audio/audio-player.js~AudioPlayer#reset",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#reseteventlisteners",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-resetEventListeners",
    "src/audio/audio-player.js~AudioPlayer#resetEventListeners",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#scrub",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-scrub",
    "src/audio/audio-player.js~AudioPlayer#scrub",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#setaudiomute",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-setAudioMute",
    "src/audio/audio-player.js~AudioPlayer#setAudioMute",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#setaudiovolume",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-setAudioVolume",
    "src/audio/audio-player.js~AudioPlayer#setAudioVolume",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#setplaybackrate",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-setPlaybackRate",
    "src/audio/audio-player.js~AudioPlayer#setPlaybackRate",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#stop",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-stop",
    "src/audio/audio-player.js~AudioPlayer#stop",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#toggleaudiomute",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-toggleAudioMute",
    "src/audio/audio-player.js~AudioPlayer#toggleAudioMute",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#toggleplayback",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-togglePlayback",
    "src/audio/audio-player.js~AudioPlayer#togglePlayback",
    "method"
  ],
  [
    "src/audio/audio-recorder.js",
    "file/src/audio/audio-recorder.js.html",
    "src/audio/audio-recorder.js",
    "file"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#activerecordingid",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-activeRecordingId",
    "src/audio/audio-recorder.js~AudioRecorder#activeRecordingId",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#addeventlistener",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-addEventListener",
    "src/audio/audio-recorder.js~AudioRecorder#addEventListener",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#audiocontext",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-audioContext",
    "src/audio/audio-recorder.js~AudioRecorder#audioContext",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#bindstopwatch",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-bindStopwatch",
    "src/audio/audio-recorder.js~AudioRecorder#bindStopwatch",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#cangetusermedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-canGetUserMedia",
    "src/audio/audio-recorder.js~AudioRecorder#canGetUserMedia",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#canmediadevicesgetusermedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-canMediaDevicesGetUserMedia",
    "src/audio/audio-recorder.js~AudioRecorder#canMediaDevicesGetUserMedia",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#canusecordovamedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-canUseCordovaMedia",
    "src/audio/audio-recorder.js~AudioRecorder#canUseCordovaMedia",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#canusemediarecorder",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-canUseMediaRecorder",
    "src/audio/audio-recorder.js~AudioRecorder#canUseMediaRecorder",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#constructor",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-constructor-constructor",
    "src/audio/audio-recorder.js~AudioRecorder#constructor",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#getaudiospecs",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-getAudioSpecs",
    "src/audio/audio-recorder.js~AudioRecorder#getAudioSpecs",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#hasusermediaapproval",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-hasUserMediaApproval",
    "src/audio/audio-recorder.js~AudioRecorder#hasUserMediaApproval",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#isrecording",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-isRecording",
    "src/audio/audio-recorder.js~AudioRecorder#isRecording",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#micinput",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-micInput",
    "src/audio/audio-recorder.js~AudioRecorder#micInput",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#record",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-record",
    "src/audio/audio-recorder.js~AudioRecorder#record",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#removealleventlisteners",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-removeAllEventListeners",
    "src/audio/audio-recorder.js~AudioRecorder#removeAllEventListeners",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#removeeventlistener",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-removeEventListener",
    "src/audio/audio-recorder.js~AudioRecorder#removeEventListener",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#requestusermedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-requestUserMedia",
    "src/audio/audio-recorder.js~AudioRecorder#requestUserMedia",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#startrecordingsession",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-startRecordingSession",
    "src/audio/audio-recorder.js~AudioRecorder#startRecordingSession",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#stop",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-stop",
    "src/audio/audio-recorder.js~AudioRecorder#stop",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#streamcallback",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-streamCallback",
    "src/audio/audio-recorder.js~AudioRecorder#streamCallback",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#togglerecording",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-toggleRecording",
    "src/audio/audio-recorder.js~AudioRecorder#toggleRecording",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#usermediaapproval",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-userMediaApproval",
    "src/audio/audio-recorder.js~AudioRecorder#userMediaApproval",
    "member"
  ],
  [
    "src/audio/audio-tools.js",
    "file/src/audio/audio-tools.js.html",
    "src/audio/audio-tools.js",
    "file"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#analysernode",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-analyserNode",
    "src/audio/audio-tools.js~VolumeMeter#analyserNode",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#audiocontext",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-audioContext",
    "src/audio/audio-tools.js~VolumeMeter#audioContext",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#constructor",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-constructor-constructor",
    "src/audio/audio-tools.js~VolumeMeter#constructor",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#getvolumeindication",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-method-getVolumeIndication",
    "src/audio/audio-tools.js~VolumeMeter#getVolumeIndication",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#stopanalyser",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-method-stopAnalyser",
    "src/audio/audio-tools.js~VolumeMeter#stopAnalyser",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#stream",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-stream",
    "src/audio/audio-tools.js~VolumeMeter#stream",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#volumeindicationcallback",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-volumeIndicationCallback",
    "src/audio/audio-tools.js~VolumeMeter#volumeIndicationCallback",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#volumeindicationcallbackargs",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-volumeIndicationCallbackArgs",
    "src/audio/audio-tools.js~VolumeMeter#volumeIndicationCallbackArgs",
    "member"
  ],
  [
    "src/audio/cordova-media-player.js",
    "file/src/audio/cordova-media-player.js.html",
    "src/audio/cordova-media-player.js",
    "file"
  ],
  [
    "src/audio/cordova-media-recorder.js",
    "file/src/audio/cordova-media-recorder.js.html",
    "src/audio/cordova-media-recorder.js",
    "file"
  ],
  [
    "src/audio/media-recorder.js",
    "file/src/audio/media-recorder.js.html",
    "src/audio/media-recorder.js",
    "file"
  ],
  [
    "src/audio/tools.js",
    "file/src/audio/tools.js.html",
    "src/audio/tools.js",
    "file"
  ],
  [
    "src/audio/tools.js~stopwatch#constructor",
    "class/src/audio/tools.js~Stopwatch.html#instance-constructor-constructor",
    "src/audio/tools.js~Stopwatch#constructor",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#registerlistener",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-registerListener",
    "src/audio/tools.js~Stopwatch#registerListener",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#reset",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-reset",
    "src/audio/tools.js~Stopwatch#reset",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#start",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-start",
    "src/audio/tools.js~Stopwatch#start",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#stop",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-stop",
    "src/audio/tools.js~Stopwatch#stop",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#stoplistening",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-stopListening",
    "src/audio/tools.js~Stopwatch#stopListening",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#tick",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-tick",
    "src/audio/tools.js~Stopwatch#tick",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#update",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-update",
    "src/audio/tools.js~Stopwatch#update",
    "method"
  ],
  [
    "src/audio/wave-packer.js",
    "file/src/audio/wave-packer.js.html",
    "src/audio/wave-packer.js",
    "file"
  ],
  [
    "src/audio/web-audio-player.js",
    "file/src/audio/web-audio-player.js.html",
    "src/audio/web-audio-player.js",
    "file"
  ],
  [
    "src/audio/web-audio-recorder.js",
    "file/src/audio/web-audio-recorder.js.html",
    "src/audio/web-audio-recorder.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]