window.esdocSearchIndex = [
  [
    "@itslanguage/sdk/webaudio/audiocontext.js~audiocontext",
    "class/src/WebAudio/AudioContext.js~AudioContext.html",
    "<span>AudioContext</span> <span class=\"search-result-import-path\">@itslanguage/sdk/WebAudio/AudioContext.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/audio-player.js~audioplayer",
    "class/src/audio/audio-player.js~AudioPlayer.html",
    "<span>AudioPlayer</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/audio-player.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/audio-recorder.js~audiorecorder",
    "class/src/audio/audio-recorder.js~AudioRecorder.html",
    "<span>AudioRecorder</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/audio-recorder.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/@itslanguage/sdk~itslanguage",
    "class/src/index.js~Itslanguage.html",
    "<span>Itslanguage</span> <span class=\"search-result-import-path\">@itslanguage/sdk/@itslanguage/sdk</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/media-recorder.js~mediarecorder",
    "class/src/audio/media-recorder.js~MediaRecorder.html",
    "<span>MediaRecorder</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/media-recorder.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/webaudio/player.js~player",
    "class/src/WebAudio/Player.js~Player.html",
    "<span>Player</span> <span class=\"search-result-import-path\">@itslanguage/sdk/WebAudio/Player.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/webaudio/recorder.js~recorder",
    "class/src/WebAudio/Recorder.js~Recorder.html",
    "<span>Recorder</span> <span class=\"search-result-import-path\">@itslanguage/sdk/WebAudio/Recorder.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/tools.js~stopwatch",
    "class/src/audio/tools.js~Stopwatch.html",
    "<span>Stopwatch</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/tools.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/audio-tools.js~volumemeter",
    "class/src/audio/audio-tools.js~VolumeMeter.html",
    "<span>VolumeMeter</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/audio-tools.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/wave-packer.js~wavepacker",
    "class/src/audio/wave-packer.js~WavePacker.html",
    "<span>WavePacker</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/wave-packer.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/web-audio-player.js~webaudioplayer",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html",
    "<span>WebAudioPlayer</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/web-audio-player.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/audio/web-audio-recorder.js~webaudiorecorder",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html",
    "<span>WebAudioRecorder</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/web-audio-recorder.js</span>",
    "class"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/analysis.js~alignchallenge",
    "function/index.html#static-function-alignChallenge",
    "<span>alignChallenge</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/analysis.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/auth/index.js~assemblescope",
    "function/index.html#static-function-assembleScope",
    "<span>assembleScope</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/auth/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/auth/index.js~authenticate",
    "function/index.html#static-function-authenticate",
    "<span>authenticate</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/auth/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/communication/index.js~authorisedrequest",
    "function/index.html#static-function-authorisedRequest",
    "<span>authorisedRequest</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/broadcaster/index.js~broadcaster",
    "variable/index.html#static-variable-broadcaster",
    "<span>broadcaster</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/broadcaster/index.js</span>",
    "variable"
  ],
  [
    "@itslanguage/sdk/api/challenges/index.js~choice",
    "variable/index.html#static-variable-choice",
    "<span>choice</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/index.js</span>",
    "variable"
  ],
  [
    "@itslanguage/sdk/api/communication/websocket.js~closewebsocketconnection",
    "function/index.html#static-function-closeWebsocketConnection",
    "<span>closeWebsocketConnection</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/websocket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/basicauth/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/basicauth/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/categories/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/categories/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/recognition.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/recognition.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/speech/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/speech/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/emailauth/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/emailauth/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/groups/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/groups/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/organisations/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/organisations/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/profile/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/profile/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/roles/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/roles/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/tenants/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/tenants/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/users/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/users/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/@itslanguage/sdk~createaudioplayer",
    "function/index.html#static-function-createAudioPlayer",
    "<span>createAudioPlayer</span> <span class=\"search-result-import-path\">@itslanguage/sdk/@itslanguage/sdk</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/@itslanguage/sdk~createaudiorecorder",
    "function/index.html#static-function-createAudioRecorder",
    "<span>createAudioRecorder</span> <span class=\"search-result-import-path\">@itslanguage/sdk/@itslanguage/sdk</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/@itslanguage/sdk~createitslsdk",
    "function/index.html#static-function-createItslSdk",
    "<span>createItslSdk</span> <span class=\"search-result-import-path\">@itslanguage/sdk/@itslanguage/sdk</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/@itslanguage/sdk~createplayer",
    "function/index.html#static-function-createPlayer",
    "<span>createPlayer</span> <span class=\"search-result-import-path\">@itslanguage/sdk/@itslanguage/sdk</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/@itslanguage/sdk~createstopwatch",
    "function/index.html#static-function-createStopwatch",
    "<span>createStopwatch</span> <span class=\"search-result-import-path\">@itslanguage/sdk/@itslanguage/sdk</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/@itslanguage/sdk~createvolumemeter",
    "function/index.html#static-function-createVolumeMeter",
    "<span>createVolumeMeter</span> <span class=\"search-result-import-path\">@itslanguage/sdk/@itslanguage/sdk</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/audio/wave-packer.js~createwaveheader",
    "function/index.html#static-function-createWAVEHeader",
    "<span>createWAVEHeader</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/wave-packer.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/utils/index.js~datatobase64",
    "function/index.html#static-function-dataToBase64",
    "<span>dataToBase64</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/utils/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/index.js~deletechallenge",
    "function/index.html#static-function-deleteChallenge",
    "<span>deleteChallenge</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/utils/audio-over-socket.js~encodeandsendaudioondataavailable",
    "function/index.html#static-function-encodeAndSendAudioOnDataAvailable",
    "<span>encodeAndSendAudioOnDataAvailable</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/utils/audio-over-socket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/analysis.js~endstreamaudio",
    "function/index.html#static-function-endStreamAudio",
    "<span>endStreamAudio</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/analysis.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/speech.js~feedback",
    "function/index.html#static-function-feedback",
    "<span>feedback</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/speech.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/index.js~feedback",
    "variable/index.html#static-variable-feedback",
    "<span>feedback</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/index.js</span>",
    "variable"
  ],
  [
    "@itslanguage/sdk/audio/audio-tools.js~generatewavesample",
    "function/index.html#static-function-generateWaveSample",
    "<span>generateWaveSample</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/audio-tools.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/categories/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/categories/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/recognition.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/recognition.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/speech/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/speech/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/speech/recordings.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/speech/recordings.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/groups/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/groups/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/organisations/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/organisations/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/roles/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/roles/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/tenants/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/tenants/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/users/index.js~getall",
    "function/index.html#static-function-getAll",
    "<span>getAll</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/users/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/categories/index.js~getallwithparentid",
    "function/index.html#static-function-getAllWithParentId",
    "<span>getAllWithParentId</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/categories/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/categories/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/categories/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/recognition.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/recognition.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/analysis.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/analysis.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/speech/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/speech/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/speech/recordings.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/speech/recordings.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/groups/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/groups/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/organisations/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/organisations/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/profile/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/profile/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/progress/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/progress/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/roles/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/roles/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/tenants/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/tenants/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/users/index.js~getbyid",
    "function/index.html#static-function-getById",
    "<span>getById</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/users/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/profile/index.js~getcurrent",
    "function/index.html#static-function-getCurrent",
    "<span>getCurrent</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/profile/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/users/index.js~getcurrent",
    "function/index.html#static-function-getCurrent",
    "<span>getCurrent</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/users/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/communication/websocket.js~getwebsocketconnection",
    "function/index.html#static-function-getWebsocketConnection",
    "<span>getWebsocketConnection</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/websocket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/auth/index.js~impersonate",
    "function/index.html#static-function-impersonate",
    "<span>impersonate</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/auth/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/speech.js~listenandreply",
    "function/index.html#static-function-listenAndReply",
    "<span>listenAndReply</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/speech.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/communication/websocket.js~makewebsocketcall",
    "function/index.html#static-function-makeWebsocketCall",
    "<span>makeWebsocketCall</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/websocket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/communication/websocket.js~openwebsocketconnection",
    "function/index.html#static-function-openWebsocketConnection",
    "<span>openWebsocketConnection</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/websocket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/speech.js~pause",
    "function/index.html#static-function-pause",
    "<span>pause</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/speech.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/recognition.js~prepare",
    "function/index.html#static-function-prepare",
    "<span>prepare</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/recognition.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/speech.js~prepare",
    "function/index.html#static-function-prepare",
    "<span>prepare</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/speech.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/analysis.js~prepare",
    "function/index.html#static-function-prepare",
    "<span>prepare</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/analysis.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/analysis.js~prepareaudio",
    "function/index.html#static-function-prepareAudio",
    "<span>prepareAudio</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/analysis.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/recognition.js~preparechallenge",
    "function/index.html#static-function-prepareChallenge",
    "<span>prepareChallenge</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/recognition.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/analysis.js~preparechallenge",
    "function/index.html#static-function-prepareChallenge",
    "<span>prepareChallenge</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/analysis.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/utils/audio-over-socket.js~prepareserverforaudio",
    "function/index.html#static-function-prepareServerForAudio",
    "<span>prepareServerForAudio</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/utils/audio-over-socket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/index.js~pronunciation",
    "variable/index.html#static-variable-pronunciation",
    "<span>pronunciation</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/index.js</span>",
    "variable"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/recognition.js~recognise",
    "function/index.html#static-function-recognise",
    "<span>recognise</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/recognition.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/choice/recognition.js~recogniseaudiostream",
    "function/index.html#static-function-recogniseAudioStream",
    "<span>recogniseAudioStream</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/choice/recognition.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/speech/recordings.js~record",
    "function/index.html#static-function-record",
    "<span>record</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/speech/recordings.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/utils/audio-over-socket.js~registerstreamforrecorder",
    "function/index.html#static-function-registerStreamForRecorder",
    "<span>registerStreamForRecorder</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/utils/audio-over-socket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/communication/index.js~request",
    "function/index.html#static-function-request",
    "<span>request</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/challenges/feedback/speech.js~resume",
    "function/index.html#static-function-resume",
    "<span>resume</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/feedback/speech.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/communication/index.js~settings",
    "variable/index.html#static-variable-settings",
    "<span>settings</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/index.js</span>",
    "variable"
  ],
  [
    "@itslanguage/sdk/api/challenges/index.js~speech",
    "variable/index.html#static-variable-speech",
    "<span>speech</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/index.js</span>",
    "variable"
  ],
  [
    "@itslanguage/sdk/api/challenges/pronunciation/analysis.js~streamaudio",
    "function/index.html#static-function-streamAudio",
    "<span>streamAudio</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/challenges/pronunciation/analysis.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/categories/index.js~update",
    "function/index.html#static-function-update",
    "<span>update</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/categories/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/communication/index.js~updatesettings",
    "function/index.html#static-function-updateSettings",
    "<span>updateSettings</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/communication/index.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/api/utils/audio-over-socket.js~waitforusermediaapproval",
    "function/index.html#static-function-waitForUserMediaApproval",
    "<span>waitForUserMediaApproval</span> <span class=\"search-result-import-path\">@itslanguage/sdk/api/utils/audio-over-socket.js</span>",
    "function"
  ],
  [
    "@itslanguage/sdk/audio/wave-packer.js~wordtoutf8bytearray",
    "function/index.html#static-function-wordToUTF8ByteArray",
    "<span>wordToUTF8ByteArray</span> <span class=\"search-result-import-path\">@itslanguage/sdk/audio/wave-packer.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/webaudio/audiocontext.js",
    "file/src/WebAudio/AudioContext.js.html",
    "src/WebAudio/AudioContext.js",
    "file"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#addeventlistener",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-method-addEventListener",
    "src/WebAudio/AudioContext.js~AudioContext#addEventListener",
    "method"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#audiocontext",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-member-audioContext",
    "src/WebAudio/AudioContext.js~AudioContext#audioContext",
    "member"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#constructor",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-constructor-constructor",
    "src/WebAudio/AudioContext.js~AudioContext#constructor",
    "method"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#error",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-member-error",
    "src/WebAudio/AudioContext.js~AudioContext#error",
    "member"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#eventlisteners",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-member-eventListeners",
    "src/WebAudio/AudioContext.js~AudioContext#eventListeners",
    "member"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#fireevent",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-method-fireEvent",
    "src/WebAudio/AudioContext.js~AudioContext#fireEvent",
    "method"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#log",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-member-log",
    "src/WebAudio/AudioContext.js~AudioContext#log",
    "member"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#removealleventlisteners",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-method-removeAllEventListeners",
    "src/WebAudio/AudioContext.js~AudioContext#removeAllEventListeners",
    "method"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#removeeventlistener",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-method-removeEventListener",
    "src/WebAudio/AudioContext.js~AudioContext#removeEventListener",
    "method"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#resumeaudiocontext",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-method-resumeAudioContext",
    "src/WebAudio/AudioContext.js~AudioContext#resumeAudioContext",
    "method"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext#suspendaudiocontext",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#instance-method-suspendAudioContext",
    "src/WebAudio/AudioContext.js~AudioContext#suspendAudioContext",
    "method"
  ],
  [
    "src/webaudio/audiocontext.js~audiocontext.createaudiocontext",
    "class/src/WebAudio/AudioContext.js~AudioContext.html#static-method-createAudioContext",
    "src/WebAudio/AudioContext.js~AudioContext.createAudioContext",
    "method"
  ],
  [
    "src/webaudio/player.js",
    "file/src/WebAudio/Player.js.html",
    "src/WebAudio/Player.js",
    "file"
  ],
  [
    "src/webaudio/player.js~player#audiobuffer",
    "class/src/WebAudio/Player.js~Player.html#instance-member-audioBuffer",
    "src/WebAudio/Player.js~Player#audioBuffer",
    "member"
  ],
  [
    "src/webaudio/player.js~player#audiobufferexists",
    "class/src/WebAudio/Player.js~Player.html#instance-method-audioBufferExists",
    "src/WebAudio/Player.js~Player#audioBufferExists",
    "method"
  ],
  [
    "src/webaudio/player.js~player#audiosource",
    "class/src/WebAudio/Player.js~Player.html#instance-member-audioSource",
    "src/WebAudio/Player.js~Player#audioSource",
    "member"
  ],
  [
    "src/webaudio/player.js~player#audiosourceexists",
    "class/src/WebAudio/Player.js~Player.html#instance-method-audioSourceExists",
    "src/WebAudio/Player.js~Player#audioSourceExists",
    "method"
  ],
  [
    "src/webaudio/player.js~player#constructor",
    "class/src/WebAudio/Player.js~Player.html#instance-constructor-constructor",
    "src/WebAudio/Player.js~Player#constructor",
    "method"
  ],
  [
    "src/webaudio/player.js~player#createbuffersource",
    "class/src/WebAudio/Player.js~Player.html#instance-method-createBufferSource",
    "src/WebAudio/Player.js~Player#createBufferSource",
    "method"
  ],
  [
    "src/webaudio/player.js~player#disconnectbuffersource",
    "class/src/WebAudio/Player.js~Player.html#instance-method-disconnectBufferSource",
    "src/WebAudio/Player.js~Player#disconnectBufferSource",
    "method"
  ],
  [
    "src/webaudio/player.js~player#gainnode",
    "class/src/WebAudio/Player.js~Player.html#instance-member-gainNode",
    "src/WebAudio/Player.js~Player#gainNode",
    "member"
  ],
  [
    "src/webaudio/player.js~player#getaudiocontext",
    "class/src/WebAudio/Player.js~Player.html#instance-method-getAudioContext",
    "src/WebAudio/Player.js~Player#getAudioContext",
    "method"
  ],
  [
    "src/webaudio/player.js~player#getbuffersource",
    "class/src/WebAudio/Player.js~Player.html#instance-method-getBufferSource",
    "src/WebAudio/Player.js~Player#getBufferSource",
    "method"
  ],
  [
    "src/webaudio/player.js~player#getcurrenttime",
    "class/src/WebAudio/Player.js~Player.html#instance-method-getCurrentTime",
    "src/WebAudio/Player.js~Player#getCurrentTime",
    "method"
  ],
  [
    "src/webaudio/player.js~player#getduration",
    "class/src/WebAudio/Player.js~Player.html#instance-method-getDuration",
    "src/WebAudio/Player.js~Player#getDuration",
    "method"
  ],
  [
    "src/webaudio/player.js~player#isplaying",
    "class/src/WebAudio/Player.js~Player.html#instance-method-isPlaying",
    "src/WebAudio/Player.js~Player#isPlaying",
    "method"
  ],
  [
    "src/webaudio/player.js~player#load",
    "class/src/WebAudio/Player.js~Player.html#instance-method-load",
    "src/WebAudio/Player.js~Player#load",
    "method"
  ],
  [
    "src/webaudio/player.js~player#mute",
    "class/src/WebAudio/Player.js~Player.html#instance-method-mute",
    "src/WebAudio/Player.js~Player#mute",
    "method"
  ],
  [
    "src/webaudio/player.js~player#pause",
    "class/src/WebAudio/Player.js~Player.html#instance-method-pause",
    "src/WebAudio/Player.js~Player#pause",
    "method"
  ],
  [
    "src/webaudio/player.js~player#pausedat",
    "class/src/WebAudio/Player.js~Player.html#instance-member-pausedAt",
    "src/WebAudio/Player.js~Player#pausedAt",
    "member"
  ],
  [
    "src/webaudio/player.js~player#play",
    "class/src/WebAudio/Player.js~Player.html#instance-method-play",
    "src/WebAudio/Player.js~Player#play",
    "method"
  ],
  [
    "src/webaudio/player.js~player#playing",
    "class/src/WebAudio/Player.js~Player.html#instance-member-playing",
    "src/WebAudio/Player.js~Player#playing",
    "member"
  ],
  [
    "src/webaudio/player.js~player#setvolume",
    "class/src/WebAudio/Player.js~Player.html#instance-method-setVolume",
    "src/WebAudio/Player.js~Player#setVolume",
    "method"
  ],
  [
    "src/webaudio/player.js~player#startedat",
    "class/src/WebAudio/Player.js~Player.html#instance-member-startedAt",
    "src/WebAudio/Player.js~Player#startedAt",
    "member"
  ],
  [
    "src/webaudio/player.js~player#stop",
    "class/src/WebAudio/Player.js~Player.html#instance-method-stop",
    "src/WebAudio/Player.js~Player#stop",
    "method"
  ],
  [
    "src/webaudio/player.js~player#volume",
    "class/src/WebAudio/Player.js~Player.html#instance-member-volume",
    "src/WebAudio/Player.js~Player#volume",
    "member"
  ],
  [
    "src/webaudio/recorder.js",
    "file/src/WebAudio/Recorder.js.html",
    "src/WebAudio/Recorder.js",
    "file"
  ],
  [
    "src/webaudio/recorder.js~recorder#audioformat",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-member-audioFormat",
    "src/WebAudio/Recorder.js~Recorder#audioFormat",
    "member"
  ],
  [
    "src/webaudio/recorder.js~recorder#channels",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-member-channels",
    "src/WebAudio/Recorder.js~Recorder#channels",
    "member"
  ],
  [
    "src/webaudio/recorder.js~recorder#constructor",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-constructor-constructor",
    "src/WebAudio/Recorder.js~Recorder#constructor",
    "method"
  ],
  [
    "src/webaudio/recorder.js~recorder#createandconnect",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-method-createAndConnect",
    "src/WebAudio/Recorder.js~Recorder#createAndConnect",
    "method"
  ],
  [
    "src/webaudio/recorder.js~recorder#createstream",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-method-createStream",
    "src/WebAudio/Recorder.js~Recorder#createStream",
    "method"
  ],
  [
    "src/webaudio/recorder.js~recorder#getaudiospecs",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-method-getAudioSpecs",
    "src/WebAudio/Recorder.js~Recorder#getAudioSpecs",
    "method"
  ],
  [
    "src/webaudio/recorder.js~recorder#mediastreamsource",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-member-mediaStreamSource",
    "src/WebAudio/Recorder.js~Recorder#mediaStreamSource",
    "member"
  ],
  [
    "src/webaudio/recorder.js~recorder#samplerate",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-member-sampleRate",
    "src/WebAudio/Recorder.js~Recorder#sampleRate",
    "member"
  ],
  [
    "src/webaudio/recorder.js~recorder#samplewidth",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-member-sampleWidth",
    "src/WebAudio/Recorder.js~Recorder#sampleWidth",
    "member"
  ],
  [
    "src/webaudio/recorder.js~recorder#startrecording",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-method-startRecording",
    "src/WebAudio/Recorder.js~Recorder#startRecording",
    "method"
  ],
  [
    "src/webaudio/recorder.js~recorder#stoprecording",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-method-stopRecording",
    "src/WebAudio/Recorder.js~Recorder#stopRecording",
    "method"
  ],
  [
    "src/webaudio/recorder.js~recorder#stream",
    "class/src/WebAudio/Recorder.js~Recorder.html#instance-member-stream",
    "src/WebAudio/Recorder.js~Recorder#stream",
    "member"
  ],
  [
    "src/api/auth/index.js",
    "file/src/api/auth/index.js.html",
    "src/api/auth/index.js",
    "file"
  ],
  [
    "src/api/basicauth/index.js",
    "file/src/api/basicauth/index.js.html",
    "src/api/basicauth/index.js",
    "file"
  ],
  [
    "src/api/broadcaster/index.js",
    "file/src/api/broadcaster/index.js.html",
    "src/api/broadcaster/index.js",
    "file"
  ],
  [
    "src/api/categories/index.js",
    "file/src/api/categories/index.js.html",
    "src/api/categories/index.js",
    "file"
  ],
  [
    "src/api/challenges/choice/index.js",
    "file/src/api/challenges/choice/index.js.html",
    "src/api/challenges/choice/index.js",
    "file"
  ],
  [
    "src/api/challenges/choice/recognition.js",
    "file/src/api/challenges/choice/recognition.js.html",
    "src/api/challenges/choice/recognition.js",
    "file"
  ],
  [
    "src/api/challenges/feedback/index.js",
    "file/src/api/challenges/feedback/index.js.html",
    "src/api/challenges/feedback/index.js",
    "file"
  ],
  [
    "src/api/challenges/feedback/speech.js",
    "file/src/api/challenges/feedback/speech.js.html",
    "src/api/challenges/feedback/speech.js",
    "file"
  ],
  [
    "src/api/challenges/index.js",
    "file/src/api/challenges/index.js.html",
    "src/api/challenges/index.js",
    "file"
  ],
  [
    "src/api/challenges/pronunciation/analysis.js",
    "file/src/api/challenges/pronunciation/analysis.js.html",
    "src/api/challenges/pronunciation/analysis.js",
    "file"
  ],
  [
    "src/api/challenges/pronunciation/index.js",
    "file/src/api/challenges/pronunciation/index.js.html",
    "src/api/challenges/pronunciation/index.js",
    "file"
  ],
  [
    "src/api/challenges/speech/index.js",
    "file/src/api/challenges/speech/index.js.html",
    "src/api/challenges/speech/index.js",
    "file"
  ],
  [
    "src/api/challenges/speech/recordings.js",
    "file/src/api/challenges/speech/recordings.js.html",
    "src/api/challenges/speech/recordings.js",
    "file"
  ],
  [
    "src/api/communication/index.js",
    "file/src/api/communication/index.js.html",
    "src/api/communication/index.js",
    "file"
  ],
  [
    "src/api/communication/websocket.js",
    "file/src/api/communication/websocket.js.html",
    "src/api/communication/websocket.js",
    "file"
  ],
  [
    "src/api/emailauth/index.js",
    "file/src/api/emailauth/index.js.html",
    "src/api/emailauth/index.js",
    "file"
  ],
  [
    "src/api/groups/index.js",
    "file/src/api/groups/index.js.html",
    "src/api/groups/index.js",
    "file"
  ],
  [
    "src/api/organisations/index.js",
    "file/src/api/organisations/index.js.html",
    "src/api/organisations/index.js",
    "file"
  ],
  [
    "src/api/profile/index.js",
    "file/src/api/profile/index.js.html",
    "src/api/profile/index.js",
    "file"
  ],
  [
    "src/api/progress/index.js",
    "file/src/api/progress/index.js.html",
    "src/api/progress/index.js",
    "file"
  ],
  [
    "src/api/roles/index.js",
    "file/src/api/roles/index.js.html",
    "src/api/roles/index.js",
    "file"
  ],
  [
    "src/api/tenants/index.js",
    "file/src/api/tenants/index.js.html",
    "src/api/tenants/index.js",
    "file"
  ],
  [
    "src/api/users/index.js",
    "file/src/api/users/index.js.html",
    "src/api/users/index.js",
    "file"
  ],
  [
    "src/api/utils/audio-over-socket.js",
    "file/src/api/utils/audio-over-socket.js.html",
    "src/api/utils/audio-over-socket.js",
    "file"
  ],
  [
    "src/api/utils/index.js",
    "file/src/api/utils/index.js.html",
    "src/api/utils/index.js",
    "file"
  ],
  [
    "src/audio/audio-player.js",
    "file/src/audio/audio-player.js.html",
    "src/audio/audio-player.js",
    "file"
  ],
  [
    "src/audio/audio-player.js~audioplayer#addeventlistener",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-addEventListener",
    "src/audio/audio-player.js~AudioPlayer#addEventListener",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#audiolevel",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-audioLevel",
    "src/audio/audio-player.js~AudioPlayer#audioLevel",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#audiomuted",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-audioMuted",
    "src/audio/audio-player.js~AudioPlayer#audioMuted",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#bindstopwatch",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-bindStopwatch",
    "src/audio/audio-player.js~AudioPlayer#bindStopwatch",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#canplay",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-canPlay",
    "src/audio/audio-player.js~AudioPlayer#canPlay",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#canuseaudio",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-canUseAudio",
    "src/audio/audio-player.js~AudioPlayer#canUseAudio",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#constructor",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-constructor-constructor",
    "src/audio/audio-player.js~AudioPlayer#constructor",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#emitter",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-emitter",
    "src/audio/audio-player.js~AudioPlayer#emitter",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getaudiovolume",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getAudioVolume",
    "src/audio/audio-player.js~AudioPlayer#getAudioVolume",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getbufferfill",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getBufferFill",
    "src/audio/audio-player.js~AudioPlayer#getBufferFill",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getcurrenttime",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getCurrentTime",
    "src/audio/audio-player.js~AudioPlayer#getCurrentTime",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getduration",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getDuration",
    "src/audio/audio-player.js~AudioPlayer#getDuration",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getplaybackrate",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getPlaybackRate",
    "src/audio/audio-player.js~AudioPlayer#getPlaybackRate",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#getplayer",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-getPlayer",
    "src/audio/audio-player.js~AudioPlayer#getPlayer",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#isaudiomuted",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-isAudioMuted",
    "src/audio/audio-player.js~AudioPlayer#isAudioMuted",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#isplaying",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-isPlaying",
    "src/audio/audio-player.js~AudioPlayer#isPlaying",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#load",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-load",
    "src/audio/audio-player.js~AudioPlayer#load",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#pause",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-pause",
    "src/audio/audio-player.js~AudioPlayer#pause",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#play",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-play",
    "src/audio/audio-player.js~AudioPlayer#play",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#playbackcompatibility",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-playbackCompatibility",
    "src/audio/audio-player.js~AudioPlayer#playbackCompatibility",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#player",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-player",
    "src/audio/audio-player.js~AudioPlayer#player",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#preload",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-preload",
    "src/audio/audio-player.js~AudioPlayer#preload",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#removeeventlistener",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-removeEventListener",
    "src/audio/audio-player.js~AudioPlayer#removeEventListener",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#reset",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-reset",
    "src/audio/audio-player.js~AudioPlayer#reset",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#reseteventlisteners",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-resetEventListeners",
    "src/audio/audio-player.js~AudioPlayer#resetEventListeners",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#scrub",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-scrub",
    "src/audio/audio-player.js~AudioPlayer#scrub",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#setaudiomute",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-setAudioMute",
    "src/audio/audio-player.js~AudioPlayer#setAudioMute",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#setaudiovolume",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-setAudioVolume",
    "src/audio/audio-player.js~AudioPlayer#setAudioVolume",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#setplaybackrate",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-setPlaybackRate",
    "src/audio/audio-player.js~AudioPlayer#setPlaybackRate",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#settings",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-settings",
    "src/audio/audio-player.js~AudioPlayer#settings",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#stop",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-stop",
    "src/audio/audio-player.js~AudioPlayer#stop",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#stopwatch",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-member-stopwatch",
    "src/audio/audio-player.js~AudioPlayer#stopwatch",
    "member"
  ],
  [
    "src/audio/audio-player.js~audioplayer#toggleaudiomute",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-toggleAudioMute",
    "src/audio/audio-player.js~AudioPlayer#toggleAudioMute",
    "method"
  ],
  [
    "src/audio/audio-player.js~audioplayer#toggleplayback",
    "class/src/audio/audio-player.js~AudioPlayer.html#instance-method-togglePlayback",
    "src/audio/audio-player.js~AudioPlayer#togglePlayback",
    "method"
  ],
  [
    "src/audio/audio-recorder.js",
    "file/src/audio/audio-recorder.js.html",
    "src/audio/audio-recorder.js",
    "file"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#activerecordingid",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-activeRecordingId",
    "src/audio/audio-recorder.js~AudioRecorder#activeRecordingId",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#addeventlistener",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-addEventListener",
    "src/audio/audio-recorder.js~AudioRecorder#addEventListener",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#audiocontext",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-audioContext",
    "src/audio/audio-recorder.js~AudioRecorder#audioContext",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#bindstopwatch",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-bindStopwatch",
    "src/audio/audio-recorder.js~AudioRecorder#bindStopwatch",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#canmediadevicesgetusermedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-canMediaDevicesGetUserMedia",
    "src/audio/audio-recorder.js~AudioRecorder#canMediaDevicesGetUserMedia",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#constructor",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-constructor-constructor",
    "src/audio/audio-recorder.js~AudioRecorder#constructor",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#emitter",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-emitter",
    "src/audio/audio-recorder.js~AudioRecorder#emitter",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#fireevent",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-fireEvent",
    "src/audio/audio-recorder.js~AudioRecorder#fireEvent",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#getaudiospecs",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-getAudioSpecs",
    "src/audio/audio-recorder.js~AudioRecorder#getAudioSpecs",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#getbestrecorder",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-getBestRecorder",
    "src/audio/audio-recorder.js~AudioRecorder#getBestRecorder",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#hasusermediaapproval",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-hasUserMediaApproval",
    "src/audio/audio-recorder.js~AudioRecorder#hasUserMediaApproval",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#ispaused",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-isPaused",
    "src/audio/audio-recorder.js~AudioRecorder#isPaused",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#isrecording",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-isRecording",
    "src/audio/audio-recorder.js~AudioRecorder#isRecording",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#micinput",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-micInput",
    "src/audio/audio-recorder.js~AudioRecorder#micInput",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#pause",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-pause",
    "src/audio/audio-recorder.js~AudioRecorder#pause",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#record",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-record",
    "src/audio/audio-recorder.js~AudioRecorder#record",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#recorder",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-recorder",
    "src/audio/audio-recorder.js~AudioRecorder#recorder",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#recordingcompatibility",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-recordingCompatibility",
    "src/audio/audio-recorder.js~AudioRecorder#recordingCompatibility",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#removealleventlisteners",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-removeAllEventListeners",
    "src/audio/audio-recorder.js~AudioRecorder#removeAllEventListeners",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#removeeventlistener",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-removeEventListener",
    "src/audio/audio-recorder.js~AudioRecorder#removeEventListener",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#requestusermedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-requestUserMedia",
    "src/audio/audio-recorder.js~AudioRecorder#requestUserMedia",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#requiregetusermedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-requireGetUserMedia",
    "src/audio/audio-recorder.js~AudioRecorder#requireGetUserMedia",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#settings",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-settings",
    "src/audio/audio-recorder.js~AudioRecorder#settings",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#startrecordingsession",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-startRecordingSession",
    "src/audio/audio-recorder.js~AudioRecorder#startRecordingSession",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#startusermedia",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-startUserMedia",
    "src/audio/audio-recorder.js~AudioRecorder#startUserMedia",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#stop",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-stop",
    "src/audio/audio-recorder.js~AudioRecorder#stop",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#stopwatch",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-stopwatch",
    "src/audio/audio-recorder.js~AudioRecorder#stopwatch",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#streamcallback",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-streamCallback",
    "src/audio/audio-recorder.js~AudioRecorder#streamCallback",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#togglerecording",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-method-toggleRecording",
    "src/audio/audio-recorder.js~AudioRecorder#toggleRecording",
    "method"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder#usermediaapproval",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#instance-member-userMediaApproval",
    "src/audio/audio-recorder.js~AudioRecorder#userMediaApproval",
    "member"
  ],
  [
    "src/audio/audio-recorder.js~audiorecorder.createaudiocontext",
    "class/src/audio/audio-recorder.js~AudioRecorder.html#static-method-createAudioContext",
    "src/audio/audio-recorder.js~AudioRecorder.createAudioContext",
    "method"
  ],
  [
    "src/audio/audio-tools.js",
    "file/src/audio/audio-tools.js.html",
    "src/audio/audio-tools.js",
    "file"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#analysernode",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-analyserNode",
    "src/audio/audio-tools.js~VolumeMeter#analyserNode",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#audiocontext",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-audioContext",
    "src/audio/audio-tools.js~VolumeMeter#audioContext",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#constructor",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-constructor-constructor",
    "src/audio/audio-tools.js~VolumeMeter#constructor",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#getvolumeindication",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-method-getVolumeIndication",
    "src/audio/audio-tools.js~VolumeMeter#getVolumeIndication",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#resumeanalyser",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-method-resumeAnalyser",
    "src/audio/audio-tools.js~VolumeMeter#resumeAnalyser",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#stopanalyser",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-method-stopAnalyser",
    "src/audio/audio-tools.js~VolumeMeter#stopAnalyser",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#stream",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-stream",
    "src/audio/audio-tools.js~VolumeMeter#stream",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#updateanalysers",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-method-updateAnalysers",
    "src/audio/audio-tools.js~VolumeMeter#updateAnalysers",
    "method"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#volumeindicationcallback",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-volumeIndicationCallback",
    "src/audio/audio-tools.js~VolumeMeter#volumeIndicationCallback",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#volumeindicationcallbackargs",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-volumeIndicationCallbackArgs",
    "src/audio/audio-tools.js~VolumeMeter#volumeIndicationCallbackArgs",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter#willanimate",
    "class/src/audio/audio-tools.js~VolumeMeter.html#instance-member-willAnimate",
    "src/audio/audio-tools.js~VolumeMeter#willAnimate",
    "member"
  ],
  [
    "src/audio/audio-tools.js~volumemeter.getaveragevolume",
    "class/src/audio/audio-tools.js~VolumeMeter.html#static-method-getAverageVolume",
    "src/audio/audio-tools.js~VolumeMeter.getAverageVolume",
    "method"
  ],
  [
    "src/audio/media-recorder.js",
    "file/src/audio/media-recorder.js.html",
    "src/audio/media-recorder.js",
    "file"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#callback",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-member-callback",
    "src/audio/media-recorder.js~MediaRecorder#callback",
    "member"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#constructor",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-constructor-constructor",
    "src/audio/media-recorder.js~MediaRecorder#constructor",
    "method"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#getencodedaudio",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-method-getEncodedAudio",
    "src/audio/media-recorder.js~MediaRecorder#getEncodedAudio",
    "method"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#isrecording",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-method-isRecording",
    "src/audio/media-recorder.js~MediaRecorder#isRecording",
    "method"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#mediarecorder",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-member-mediaRecorder",
    "src/audio/media-recorder.js~MediaRecorder#mediaRecorder",
    "member"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#record",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-method-record",
    "src/audio/media-recorder.js~MediaRecorder#record",
    "method"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#recordedblob",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-member-recordedBlob",
    "src/audio/media-recorder.js~MediaRecorder#recordedBlob",
    "member"
  ],
  [
    "src/audio/media-recorder.js~mediarecorder#stop",
    "class/src/audio/media-recorder.js~MediaRecorder.html#instance-method-stop",
    "src/audio/media-recorder.js~MediaRecorder#stop",
    "method"
  ],
  [
    "src/audio/tools.js",
    "file/src/audio/tools.js.html",
    "src/audio/tools.js",
    "file"
  ],
  [
    "src/audio/tools.js~stopwatch#constructor",
    "class/src/audio/tools.js~Stopwatch.html#instance-constructor-constructor",
    "src/audio/tools.js~Stopwatch#constructor",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#emitter",
    "class/src/audio/tools.js~Stopwatch.html#instance-member-emitter",
    "src/audio/tools.js~Stopwatch#emitter",
    "member"
  ],
  [
    "src/audio/tools.js~stopwatch#interval",
    "class/src/audio/tools.js~Stopwatch.html#instance-member-interval",
    "src/audio/tools.js~Stopwatch#interval",
    "member"
  ],
  [
    "src/audio/tools.js~stopwatch#registerlistener",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-registerListener",
    "src/audio/tools.js~Stopwatch#registerListener",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#reset",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-reset",
    "src/audio/tools.js~Stopwatch#reset",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#start",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-start",
    "src/audio/tools.js~Stopwatch#start",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#stop",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-stop",
    "src/audio/tools.js~Stopwatch#stop",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#stoplistening",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-stopListening",
    "src/audio/tools.js~Stopwatch#stopListening",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#tick",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-tick",
    "src/audio/tools.js~Stopwatch#tick",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#tickcb",
    "class/src/audio/tools.js~Stopwatch.html#instance-member-tickCb",
    "src/audio/tools.js~Stopwatch#tickCb",
    "member"
  ],
  [
    "src/audio/tools.js~stopwatch#update",
    "class/src/audio/tools.js~Stopwatch.html#instance-method-update",
    "src/audio/tools.js~Stopwatch#update",
    "method"
  ],
  [
    "src/audio/tools.js~stopwatch#value",
    "class/src/audio/tools.js~Stopwatch.html#instance-member-value",
    "src/audio/tools.js~Stopwatch#value",
    "member"
  ],
  [
    "src/audio/wave-packer.js",
    "file/src/audio/wave-packer.js.html",
    "src/audio/wave-packer.js",
    "file"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#channels",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-member-channels",
    "src/audio/wave-packer.js~WavePacker#channels",
    "member"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#clear",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-clear",
    "src/audio/wave-packer.js~WavePacker#clear",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#encodewav",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-encodeWAV",
    "src/audio/wave-packer.js~WavePacker#encodeWAV",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#exportmonowav",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-exportMonoWAV",
    "src/audio/wave-packer.js~WavePacker#exportMonoWAV",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#exportwav",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-exportWAV",
    "src/audio/wave-packer.js~WavePacker#exportWAV",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#init",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-init",
    "src/audio/wave-packer.js~WavePacker#init",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#interleave",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-interleave",
    "src/audio/wave-packer.js~WavePacker#interleave",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#recbuffersl",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-member-recBuffersL",
    "src/audio/wave-packer.js~WavePacker#recBuffersL",
    "member"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#recbuffersr",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-member-recBuffersR",
    "src/audio/wave-packer.js~WavePacker#recBuffersR",
    "member"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#reclength",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-member-recLength",
    "src/audio/wave-packer.js~WavePacker#recLength",
    "member"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#record",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-record",
    "src/audio/wave-packer.js~WavePacker#record",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#recordstreaming",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-method-recordStreaming",
    "src/audio/wave-packer.js~WavePacker#recordStreaming",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#recording",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-member-recording",
    "src/audio/wave-packer.js~WavePacker#recording",
    "member"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#recordingsamplerate",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-member-recordingSampleRate",
    "src/audio/wave-packer.js~WavePacker#recordingSampleRate",
    "member"
  ],
  [
    "src/audio/wave-packer.js~wavepacker#samplerate",
    "class/src/audio/wave-packer.js~WavePacker.html#instance-member-sampleRate",
    "src/audio/wave-packer.js~WavePacker#sampleRate",
    "member"
  ],
  [
    "src/audio/wave-packer.js~wavepacker.mergebuffers",
    "class/src/audio/wave-packer.js~WavePacker.html#static-method-mergeBuffers",
    "src/audio/wave-packer.js~WavePacker.mergeBuffers",
    "method"
  ],
  [
    "src/audio/wave-packer.js~wavepacker.writeutfbytes",
    "class/src/audio/wave-packer.js~WavePacker.html#static-method-writeUTFBytes",
    "src/audio/wave-packer.js~WavePacker.writeUTFBytes",
    "method"
  ],
  [
    "src/audio/web-audio-player.js",
    "file/src/audio/web-audio-player.js.html",
    "src/audio/web-audio-player.js",
    "file"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#canplay",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-canPlay",
    "src/audio/web-audio-player.js~WebAudioPlayer#canPlay",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#constructor",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-constructor-constructor",
    "src/audio/web-audio-player.js~WebAudioPlayer#constructor",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#getaudiovolume",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-getAudioVolume",
    "src/audio/web-audio-player.js~WebAudioPlayer#getAudioVolume",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#getbufferfill",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-getBufferFill",
    "src/audio/web-audio-player.js~WebAudioPlayer#getBufferFill",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#getcurrenttime",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-getCurrentTime",
    "src/audio/web-audio-player.js~WebAudioPlayer#getCurrentTime",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#getduration",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-getDuration",
    "src/audio/web-audio-player.js~WebAudioPlayer#getDuration",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#getplaybackrate",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-getPlaybackRate",
    "src/audio/web-audio-player.js~WebAudioPlayer#getPlaybackRate",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#initplayer",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-initPlayer",
    "src/audio/web-audio-player.js~WebAudioPlayer#initPlayer",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#isplaying",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-isPlaying",
    "src/audio/web-audio-player.js~WebAudioPlayer#isPlaying",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#load",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-load",
    "src/audio/web-audio-player.js~WebAudioPlayer#load",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#pause",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-pause",
    "src/audio/web-audio-player.js~WebAudioPlayer#pause",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#pauseisstop",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-member-pauseIsStop",
    "src/audio/web-audio-player.js~WebAudioPlayer#pauseIsStop",
    "member"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#play",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-play",
    "src/audio/web-audio-player.js~WebAudioPlayer#play",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#preload",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-preload",
    "src/audio/web-audio-player.js~WebAudioPlayer#preload",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#reset",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-reset",
    "src/audio/web-audio-player.js~WebAudioPlayer#reset",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#scrub",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-scrub",
    "src/audio/web-audio-player.js~WebAudioPlayer#scrub",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#setaudiovolume",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-setAudioVolume",
    "src/audio/web-audio-player.js~WebAudioPlayer#setAudioVolume",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#setplaybackrate",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-setPlaybackRate",
    "src/audio/web-audio-player.js~WebAudioPlayer#setPlaybackRate",
    "method"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#settings",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-member-settings",
    "src/audio/web-audio-player.js~WebAudioPlayer#settings",
    "member"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#sound",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-member-sound",
    "src/audio/web-audio-player.js~WebAudioPlayer#sound",
    "member"
  ],
  [
    "src/audio/web-audio-player.js~webaudioplayer#stop",
    "class/src/audio/web-audio-player.js~WebAudioPlayer.html#instance-method-stop",
    "src/audio/web-audio-player.js~WebAudioPlayer#stop",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js",
    "file/src/audio/web-audio-recorder.js.html",
    "src/audio/web-audio-recorder.js",
    "file"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#channels",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-member-channels",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#channels",
    "member"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#constructor",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-constructor-constructor",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#constructor",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#getaudiospecs",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-method-getAudioSpecs",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#getAudioSpecs",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#getencodedaudio",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-method-getEncodedAudio",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#getEncodedAudio",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#ispaused",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-method-isPaused",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#isPaused",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#isrecording",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-method-isRecording",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#isRecording",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#packer",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-member-packer",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#packer",
    "member"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#pause",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-method-pause",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#pause",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#paused",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-member-paused",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#paused",
    "member"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#record",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-method-record",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#record",
    "method"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#recordedsamplerate",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-member-recordedSampleRate",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#recordedSampleRate",
    "member"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#recorder",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-member-recorder",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#recorder",
    "member"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#recording",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-member-recording",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#recording",
    "member"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#samplerate",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-member-sampleRate",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#sampleRate",
    "member"
  ],
  [
    "src/audio/web-audio-recorder.js~webaudiorecorder#stop",
    "class/src/audio/web-audio-recorder.js~WebAudioRecorder.html#instance-method-stop",
    "src/audio/web-audio-recorder.js~WebAudioRecorder#stop",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~itslanguage#authentication",
    "class/src/index.js~Itslanguage.html#instance-member-authentication",
    "src/index.js~Itslanguage#authentication",
    "member"
  ],
  [
    "src/index.js~itslanguage#basicauth",
    "class/src/index.js~Itslanguage.html#instance-member-basicauth",
    "src/index.js~Itslanguage#basicauth",
    "member"
  ],
  [
    "src/index.js~itslanguage#broadcaster",
    "class/src/index.js~Itslanguage.html#instance-member-broadcaster",
    "src/index.js~Itslanguage#broadcaster",
    "member"
  ],
  [
    "src/index.js~itslanguage#categories",
    "class/src/index.js~Itslanguage.html#instance-member-categories",
    "src/index.js~Itslanguage#categories",
    "member"
  ],
  [
    "src/index.js~itslanguage#challenges",
    "class/src/index.js~Itslanguage.html#instance-member-challenges",
    "src/index.js~Itslanguage#challenges",
    "member"
  ],
  [
    "src/index.js~itslanguage#communication",
    "class/src/index.js~Itslanguage.html#instance-member-communication",
    "src/index.js~Itslanguage#communication",
    "member"
  ],
  [
    "src/index.js~itslanguage#constructor",
    "class/src/index.js~Itslanguage.html#instance-constructor-constructor",
    "src/index.js~Itslanguage#constructor",
    "method"
  ],
  [
    "src/index.js~itslanguage#emailauth",
    "class/src/index.js~Itslanguage.html#instance-member-emailauth",
    "src/index.js~Itslanguage#emailauth",
    "member"
  ],
  [
    "src/index.js~itslanguage#groups",
    "class/src/index.js~Itslanguage.html#instance-member-groups",
    "src/index.js~Itslanguage#groups",
    "member"
  ],
  [
    "src/index.js~itslanguage#organisations",
    "class/src/index.js~Itslanguage.html#instance-member-organisations",
    "src/index.js~Itslanguage#organisations",
    "member"
  ],
  [
    "src/index.js~itslanguage#profile",
    "class/src/index.js~Itslanguage.html#instance-member-profile",
    "src/index.js~Itslanguage#profile",
    "member"
  ],
  [
    "src/index.js~itslanguage#progress",
    "class/src/index.js~Itslanguage.html#instance-member-progress",
    "src/index.js~Itslanguage#progress",
    "member"
  ],
  [
    "src/index.js~itslanguage#roles",
    "class/src/index.js~Itslanguage.html#instance-member-roles",
    "src/index.js~Itslanguage#roles",
    "member"
  ],
  [
    "src/index.js~itslanguage#tenants",
    "class/src/index.js~Itslanguage.html#instance-member-tenants",
    "src/index.js~Itslanguage#tenants",
    "member"
  ],
  [
    "src/index.js~itslanguage#users",
    "class/src/index.js~Itslanguage.html#instance-member-users",
    "src/index.js~Itslanguage#users",
    "member"
  ],
  [
    "src/index.js~itslanguage#utils",
    "class/src/index.js~Itslanguage.html#instance-member-utils",
    "src/index.js~Itslanguage#utils",
    "member"
  ],
  [
    "src/index.js~itslanguage#version",
    "class/src/index.js~Itslanguage.html#instance-member-version",
    "src/index.js~Itslanguage#version",
    "member"
  ]
]