name: Release npm packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - name: Store build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build

  release:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        package: [api, player, recorder]

    steps:
      - name: Releasing @itslanguage/${{ matrix.package }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@itslanguage'
      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Release @itslanguage/${{ matrix.package }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ matrix.package }}
          check-version: true
        env:
          PACKAGE_NAME: ${{ matrix.package }}
      - if: steps.publish.outputs.old-version != steps.publish.outputs.version
        run: |
          echo "@itslanguage/${PACKAGE_NAME} version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
