name: Release npm packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - name: Store build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Releasing packages
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@itslanguage'
      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Release @itslanguage/api
        run: npm publish ./api
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release @itslanguage/player
        run: npm publish ./player
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release @itslanguage/recorder
        run: npm publish ./recorder
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
